### ISSUE TITLE
Tri colour and mono colour  122x250 Feather Wings -  not displaying correctly (bottom/top rows of pixels)

### ISSUE THREAD

**Issue by dave-ct** [adafruit/Adafruit_CircuitPython_SSD1680#10]
Feather: Adafruit CircuitPython 8.0.0 on 2023-02-06; Adafruit Feather ESP32S2 with ESP32S2 (4M Flash 2M PSRAM)
Featherwing Impacted: 2.13 122x250 mono [https://www.adafruit.com/product/4195](https://www.adafruit.com/product/4195)  and 2.13 122x250 Tri-colour [https://www.adafruit.com/product/4814](https://www.adafruit.com/product/4814 )

Issue: Oringally thought an issue with the mono display where had to adjust the size of the screen from 122 to 127 to be able to use the whole screen where rows at the bottom where not updating and then had to adjust when drawing text and shapes with displayio by adding an offset on the y-axis.  Have since tested both the mono and and tricolour featherwings with the exmaple code for the SSD1680 (exmaple syays it is for the tri colour one) and both have the same issue where there are rows are the bottom not getting updated and looks like the top it not aligned (see picture below).  Looks like could be an issue with [https://github.com/adafruit/Adafruit_CircuitPython_SSD1680](https://github.com/adafruit/Adafruit_CircuitPython_SSD1680).  I dont have any alternate feathers to see if it just this feather type or the code. 

Oringal issue on Forum for Mono display with similar pictures - [https://forums.adafruit.com/viewtopic.php?t=198711](https://forums.adafruit.com/viewtopic.php?t=198711)

Exmaple fix for example file on pull request but seems like a work around now - #9 

Picture of the tri colour display (look at bottom and top rows):
![IMG_3537](https://user-images.githubusercontent.com/17012929/219113249-4785b03b-0c79-4885-8553-2317557e8001.jpeg)

@tannewt relating to pull request #9 but looks like the issue is not with the exmample file.

**Comment by tannewt** [comment]
Ya, as @makermelissa said on the PR. I think this is an incorrect colstart or rowstart value. Setting those will shift the data written to the driver IC memory.

**Comment by dave-ct** [comment]
fixed in #9
