### ISSUE TITLE
The wait time in the examples is incorrect -- should be display.time_to_refresh not 120

### ISSUE THREAD

**Issue by pedasmith** [adafruit/Adafruit_CircuitPython_SSD1680#15]
The wait times in the examples should be updated with the latest information. The current wait time is  180 seconds (3 minutes), not 120 seconds (2 minutes). And the display now includes a display.time_to_refresh which should always be preferred.

I've updated the code (see incoming PR) for the feather and the simpletest, but did not update the others.

**Comment by makermelissa** [comment]
Fixed via #16.
