### ISSUE TITLE
`__init__()` arguments are not Pin objects

### ISSUE THREAD

**Issue by FoamyGuy** [adafruit/Adafruit_CircuitPython_SSD1680#7]
We recently changed argument names for initializing the ESP32SPI library to use the suffix _dio rather than _pin because the arguments need to be instantiated DigitalInOut objects, not microcontroller.Pin objects.

See: adafruit/Adafruit_CircuitPython_ESP32SPI#121

This library uses the same *_pin names for it's arguments which are also expected to the DigitalInOuts rather than Pins.

I think we'll want to change the names here and any other libraries that have _pin to keep things consistent across libraries.

**Comment by jposada202020** [comment]
Are we referring here to the example code. If that is the case I could make a PR for that. Thanks :)

**Comment by makermelissa** [comment]
I've been diving into the eink code over the past few days and in the case of this library, pins should be used and not DigitalInOut object.
